# Generated by Django 5.1.15 on 2026-06-14 13:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RAWGCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rawg_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('cover_url', models.URLField(blank=True, max_length=500)),
                ('genre', models.CharField(blank=True, max_length=200)),
                ('developer', models.CharField(blank=True, max_length=200)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('metacritic_score', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('platforms_json', models.TextField(blank=True)),
                ('cached_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'RAWG Cache',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('playing', '🎮 Jogando'), ('completed', '✅ Zerado'), ('abandoned', '❌ Abandonado'), ('queued', '⏳ Na Fila'), ('wishlist', '🌟 Wishlist'), ('paused', '⏸️ Pausado')], default='queued', max_length=20)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('review', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('hours_played', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('rawg_id', models.IntegerField(blank=True, null=True)),
                ('cover_url', models.URLField(blank=True, max_length=500)),
                ('genre', models.CharField(blank=True, max_length=200)),
                ('developer', models.CharField(blank=True, max_length=200)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('metacritic_score', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('ai_insights', models.TextField(blank=True)),
                ('ai_generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL)),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.platform')),
                ('tags', models.ManyToManyField(blank=True, to='games.tag')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=300)),
                ('avatar_url', models.URLField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('favorite_genre', models.CharField(blank=True, max_length=100)),
                ('is_public', models.BooleanField(default=True, help_text='Perfil visível para outros usuários')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Aceito'), ('blocked', 'Bloqueado')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('from_user', 'to_user')},
            },
        ),
        migrations.CreateModel(
            name='FavoritedGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_games', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('user', 'game')},
            },
        ),
    ]
